version: 2

before:
  hooks:
    - cargo install --locked cargo-zigbuild

builds:
  - id: gitnow
    builder: rust
    binary: gitnow
    dir: .
    targets:
      - aarch64-apple-darwin
      - x86_64-unknown-linux-gnu
      - aarch64-unknown-linux-gnu
    flags:
      - --release
      - -p=gitnow

archives:
  - id: gitnow
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

gitea_urls:
  api: https://git.kjuulh.io/api/v1
  download: https://git.kjuulh.io
  skip_tls_verify: false

release:
  gitea:
    owner: kjuulh
    name: gitnow
  draft: false
  prerelease: auto
  name_template: "v{{ .Version }}"
  mode: keep-existing

brews:
  - name: gitnow
    repository:
      owner: kjuulh
      name: homebrew-tap
      token: "{{ .Env.RELEASE_TOKEN }}"
    directory: Formula
    url_template: "https://git.kjuulh.io/kjuulh/gitnow/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    homepage: "https://gitnow-client.prod.kjuulh.app"
    description: "Git Now is a utility for easily navigating git projects from common upstream providers."
    install: |
      bin.install "gitnow"
    caveats: |
      To enable shell integration, add this to your .zshrc:

        eval "$(gitnow init zsh)"
