FROM debian:trixie-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    git \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Install mise
ENV MISE_INSTALL_PATH="/usr/local/bin/mise"
RUN curl https://mise.run | sh

WORKDIR /build
COPY mise.toml .
RUN mise trust && mise install

COPY . .

ENTRYPOINT ["mise", "run"]
CMD ["release"]
